# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'read_view/Child_read_win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1061, 848)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1061, 851))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_chapter = QtWidgets.QVBoxLayout()
        self.verticalLayout_chapter.setObjectName("verticalLayout_chapter")
        self.Chapter_label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Chapter_label.sizePolicy().hasHeightForWidth())
        self.Chapter_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Chapter_label.setFont(font)
        self.Chapter_label.setLineWidth(3)
        self.Chapter_label.setTextFormat(QtCore.Qt.AutoText)
        self.Chapter_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Chapter_label.setObjectName("Chapter_label")
        self.verticalLayout_chapter.addWidget(self.Chapter_label)
        self.chapter = QtWidgets.QListWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chapter.sizePolicy().hasHeightForWidth())
        self.chapter.setSizePolicy(sizePolicy)
        self.chapter.setMaximumSize(QtCore.QSize(500, 16777215))
        self.chapter.setSizeIncrement(QtCore.QSize(35, 0))
        self.chapter.setBaseSize(QtCore.QSize(30, 0))
        self.chapter.setObjectName("chapter")
        self.verticalLayout_chapter.addWidget(self.chapter)
        self.horizontalLayout.addLayout(self.verticalLayout_chapter)
        self.content = QtWebEngineWidgets.QWebEngineView(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.content.sizePolicy().hasHeightForWidth())
        self.content.setSizePolicy(sizePolicy)
        self.content.setObjectName("content")
        self.horizontalLayout.addWidget(self.content)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Chapter_label.setText(_translate("Form", "Chapter"))
from PyQt5 import QtWebEngineWidgets
